package:
  name: pyem
  version: 0.70

source:
  path: .

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .
  entry_points:
    - cfsc.py = pyem.cli.cfsc:_main_
    - csparc2star.py = pyem.cli.csparc2star:_main_
    - ctf2star.py = pyem.cli.ctf2star:_main_
    - disparticle.py = pyem.cli.disparticle:_main_
    - emcalc.py = pyem.cli.emcalc:_main_
    - map.py = pyem.cli.map:_main_
    - mask.py = pyem.cli.mask:_main_
    - mcstar.py = pyem.cli.mcstar:_main_
    - normalize.py = pyem.cli.normalize:_main_
    - par2star.py = pyem.cli.par2star:_main_
    - project.py = pyem.cli.project:_main_
    - projection_subtraction.py = pyem.cli.projection_subtraction:_main_
    - stack.py = pyem.cli.stack:_main_
    - star.py = pyem.cli.star:_main_
    - star2bild.py = pyem.cli.star2bild:_main_
    - subparticles.py = pyem.cli.subparticles:_main_
    - varmap.py = pyem.cli.varmap:_main_

requirements:
  build:
  host:
    - python >=3.12
    - pip
    - setuptools
  run:
    - python >=3.12
    - numba >=0.61.2
    - numpy
    - numexpr
    - scipy
    - matplotlib-base
    - seaborn
    - pandas
    - pathos
    - pyfftw
    - healpy
    - natsort
    - starfile
    - rich

about:
  home: https://github.com/JohannesSchuster/pyem
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: Python programs for electron microscopy
  description: |
    Python programs for electron microscopy.
    Cite as: Asarnow, D., Palovcak, E., Cheng, Y. UCSF pyem v0.5. Zenodo https://doi.org/10.5281/zenodo.3576630 (2019)
  dev_url: https://github.com/JohannesSchuster/pyem

conda:
  channels:
    - conda-forge
    - defaults
