package:
  name: pyem
  version: 0.5

source:
  path: .

build:
  number: 0
  entry_points:
    - cfsc.py = cfsc:_main_
    - csparc2star.py = csparc2star:_main_
    - ctf2star.py = ctf2star:_main_
    - disparticle.py = disparticle:_main_
    - emcalc.py = emcalc:_main_
    - map.py = map:_main_
    - mask.py = map:_main_
    - mcstar.py = mcstar:_main_
    - par2star.py = par2star:_main_
    - project.py = project:_main_
    - projection_subtraction.py = projection_subtraction:_main_
    - stack.py = stack:_main_
    - star.py = star:_main_
    - star2bild.py = star2bild:_main_
    - subparticles.py = subparticles:_main_
    - varmap.py = varmap:_main_

requirements:
  build:
    - python
    - setuptools
  run:
    - python >=3.7
    - numba >=0.41
    - numpy >=1.14
    - scipy >=1.2
    - matplotlib >=2.2
    - seaborn >=0.9
    - pandas >=0.23.4
    - pathos >=0.2.1
    - pyfftw >=0.10
    - healpy >=1.11
    - natsort >=6.0
    - starfile >=0.5.2

about:
  home: https://github.com/asarnow/pyem
  license: GNU General Public License v3.0
  summary: A collection of Python modules and command-line utilities for electron microscopy of biological samples.

conda:
  channels:
    - conda-forge
    - defaults